//! HDR histogram wrappers for per-step latency capture.
//!
//! Records request durations in microseconds with 3 significant figures,
//! covering 1us..60s.

use std::io::Write;
use std::path::Path;

use hdrhistogram::serialization::{Serializer, V2DeflateSerializer};
use hdrhistogram::Histogram;

/// 1us .. 60s, 3 significant figures.
pub fn new_latency_histogram() -> Histogram<u64> {
    Histogram::<u64>::new_with_bounds(1, 60_000_000, 3).expect("valid hdr bounds")
}

/// Snapshot of percentile values (microseconds).
#[derive(Debug, Clone, Copy, serde::Serialize)]
pub struct Percentiles {
    pub p50_us: u64,
    pub p90_us: u64,
    pub p99_us: u64,
    pub p999_us: u64,
    pub max_us: u64,
}

impl Percentiles {
    pub fn from_histogram(h: &Histogram<u64>) -> Self {
        Self {
            p50_us: h.value_at_percentile(50.0),
            p90_us: h.value_at_percentile(90.0),
            p99_us: h.value_at_percentile(99.0),
            p999_us: h.value_at_percentile(99.9),
            max_us: h.max(),
        }
    }
}

/// Write an HDR histogram to disk in `.hgrm` text format (the canonical
/// hdrhistogram CLI format) plus a base64-encoded V2-deflate binary blob
/// next to it for downstream tooling.
pub fn write_hgrm(h: &Histogram<u64>, path: &Path) -> std::io::Result<()> {
    let mut out = std::fs::File::create(path)?;
    writeln!(out, "# HDR histogram (latency, microseconds)")?;
    writeln!(out, "# generated by extenddb-bench {}", env!("CARGO_PKG_VERSION"))?;
    writeln!(out, "# total_count={} min={} max={} mean={:.2} stddev={:.2}",
        h.len(), h.min(), h.max(), h.mean(), h.stdev())?;
    writeln!(out, "Value     Percentile TotalCount 1/(1-Percentile)")?;
    for q in PERCENTILES {
        let v = h.value_at_quantile(*q);
        let cumulative = h.iter_quantiles(1).find(|i| i.quantile() >= *q)
            .map(|i| i.count_since_last_iteration() as u64)
            .unwrap_or(0);
        let one_over = if *q < 1.0 { 1.0 / (1.0 - *q) } else { f64::INFINITY };
        writeln!(out, "{:>9} {:>10.6} {:>10} {:>16.2}", v, q, cumulative, one_over)?;
    }
    writeln!(out, "#[Mean    = {:.3}, StdDeviation   = {:.3}]", h.mean(), h.stdev())?;
    writeln!(out, "#[Max     = {}, Total count    = {}]", h.max(), h.len())?;

    // V2-deflate serialized blob, base64-encoded, on a single line so downstream
    // can reconstitute the histogram exactly.
    let mut serializer = V2DeflateSerializer::new();
    let mut buf: Vec<u8> = Vec::new();
    serializer.serialize(h, &mut buf).map_err(std::io::Error::other)?;
    let encoded = base64_encode(&buf);
    writeln!(out, "#[serialized:v2deflate:{}]", encoded)?;
    Ok(())
}

const PERCENTILES: &[f64] = &[
    0.500, 0.750, 0.900, 0.950, 0.990, 0.995, 0.999, 0.9999, 1.0,
];

/// Simple base64 (RFC 4648) encoder. Avoids pulling in another dep.
fn base64_encode(bytes: &[u8]) -> String {
    const ALPHABET: &[u8; 64] =
        b"ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/";
    let mut out = String::with_capacity((bytes.len() + 2) / 3 * 4);
    let chunks = bytes.chunks(3);
    for chunk in chunks {
        let b0 = chunk[0] as u32;
        let b1 = chunk.get(1).copied().unwrap_or(0) as u32;
        let b2 = chunk.get(2).copied().unwrap_or(0) as u32;
        let n = (b0 << 16) | (b1 << 8) | b2;
        out.push(ALPHABET[((n >> 18) & 0x3f) as usize] as char);
        out.push(ALPHABET[((n >> 12) & 0x3f) as usize] as char);
        if chunk.len() > 1 {
            out.push(ALPHABET[((n >> 6) & 0x3f) as usize] as char);
        } else {
            out.push('=');
        }
        if chunk.len() > 2 {
            out.push(ALPHABET[(n & 0x3f) as usize] as char);
        } else {
            out.push('=');
        }
    }
    out
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn percentiles_roundtrip() {
        let mut h = new_latency_histogram();
        for i in 1..=1000 {
            h.record(i * 10).unwrap();
        }
        let p = Percentiles::from_histogram(&h);
        assert!(p.p50_us > 0);
        assert!(p.p99_us >= p.p90_us);
        assert!(p.p999_us >= p.p99_us);
    }

    #[test]
    fn write_hgrm_smoke() {
        let mut h = new_latency_histogram();
        for i in 1..=100 {
            h.record(i * 100).unwrap();
        }
        let dir = tempdir();
        let path = dir.join("a.hgrm");
        write_hgrm(&h, &path).unwrap();
        let text = std::fs::read_to_string(&path).unwrap();
        assert!(text.contains("Percentile"));
        assert!(text.contains("#[serialized:v2deflate:"));
    }

    fn tempdir() -> std::path::PathBuf {
        let dir = std::env::temp_dir().join(format!("hdr-test-{}", std::process::id()));
        std::fs::create_dir_all(&dir).unwrap();
        dir
    }
}
